Feat/s3 public access block
org-formation/aws-resource-providers pull request #12
Opened 2020-08-29 17:45 UTC by OlafConijn

what do you think about:
- ./src/common.ts?
- behavior on delete. regardless of what what was configured before it will be set to all false.... does that make sense?

2020-08-29 19:17 UTC, eduardomourar reviewed
If you run the contract test from CFN CLI, the delete will fail if you can still retrieve the resource afterwards: https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-test-contract.html

2020-08-29 19:17 UTC, eduardomourar commented on s3/public-access-block/src/handlers.ts
> +    putAccountPublicAccessBlock(action, args, {
I would use the delete call itself: https://docs.aws.amazon.com/AmazonS3/latest/API/API_control_DeletePublicAccessBlock.html

2020-08-29 20:01 UTC, OlafConijn commented on s3/public-access-block/src/handlers.ts
> +    putAccountPublicAccessBlock(action, args, {
missed that one. makes sense. 

Makes me think whether to have create fail if the resource was already created prior? (only allow create if getPublicAccessBlock returns `NoSuchPublicAccessBlockConfiguration`).

To be honest i think that would be a bit too much. it would make using these resources quite complex if someone already played around with settings. 

I would be on the user friendly side here as opposed to the CFN purist side i guess.

2020-08-30 23:43 UTC, eduardomourar commented on s3/public-access-block/src/handlers.ts
> +    const accountId = await getAccountId(args.session);
with the [new rpdk v0.3.2](https://github.com/eduardomourar/cloudformation-cli-typescript-plugin/releases/tag/v0.3.2), you can now retrieve that directly using `request.awsAccountId`

2020-08-31 00:04 UTC, OlafConijn commented on s3/public-access-block/src/handlers.ts
> +const getAccountId = async (session: SessionProxy): Promise<string> => {
i saw it on the ResourceHandlerRequest interface, dont believe i ever got an actual value from the runtime object.

example request from logging:
```
"request": {
                "clientRequestToken": "49493d4a-4b74-91e5-8f1c-f5ac46e14e97",
                "desiredResourceState": {
                    "BlockPublicAcls": true,
                    "BlockPublicPolicy": false,
                    "IgnorePublicAcls": true,
                    "RestrictPublicBuckets": true,
                },
                "previousResourceState": {},
                "logicalResourceIdentifier": "S3AccountPublicAccessBlock"
            },
```

2020-08-31 00:05 UTC, OlafConijn commented on s3/public-access-block/community-s3-publicaccessblock.json
> +                "sts:GetCallerIdentity"
the sts:GetCallerIdentity? yes. i guess... but until i figure out how to get the accountId from someplace else ;)

2020-08-31 00:06 UTC, eduardomourar commented on s3/public-access-block/src/handlers.ts
> +const getAccountId = async (session: SessionProxy): Promise<string> => {
yes, i just released v0.3.2 to expose the additional properties: `desiredResourceTags`, `previousResourceTags`, `systemTags`, `awsAccountId`, `region` and `awsPartition`

2020-08-31 00:14 UTC, OlafConijn commented on s3/public-access-block/src/handlers.ts
> +const getAccountId = async (session: SessionProxy): Promise<string> => {
yes, worked :). thanks!

2020-08-31 01:07 UTC, OlafConijn commented on s3/public-access-block/src/handlers.ts
> +    putAccountPublicAccessBlock(action, args, {
I do see the advantage of adhering to the contract tests. I do wonder whether we will be able to adhere to all the expectations because not everything neatly maps to a resource (e.g. ServiceQuotas).

Also makes me wonder whether we would be able to import a pre-existing PublicAccessBlockConfiguration and how that would work with different regions. Asking users to delete using the cli (console doesnt support it) before being able to use the resource in cloudformation is quite a cost...

2020-08-31 01:22 UTC, eduardomourar commented on s3/public-access-block/src/handlers.ts
> +    putAccountPublicAccessBlock(action, args, {
i believe we need to create in org-formation cli a step prior to registering the resources where we check for pre-existing resources... very much likely the bootstrap step in the CDK

2020-08-31 01:25 UTC, OlafConijn commented on s3/public-access-block/src/handlers.ts
> +    putAccountPublicAccessBlock(action, args, {
I think if we are smart about it we might be able to have an init step (like org-formation init) that creates the right cloudformation scripts using the List/Read entries. will that not be pretty awesome?

but maybe post v1

2020-09-02 15:52 UTC, eduardomourar requested changes
with the changes suggested, I am happy with the contract test results:
```
handler_create.py::contract_create_delete PASSED                                                                                                         [  7%]
handler_create.py::contract_invalid_create FAILED                                                                                                        [ 15%]
handler_create.py::contract_create_duplicate SKIPPED                                                                                                     [ 23%]
handler_create.py::contract_create_read_success PASSED                                                                                                   [ 30%]
handler_delete.py::contract_delete_read PASSED                                                                                                           [ 38%]
handler_delete.py::contract_delete_update FAILED                                                                                                         [ 46%]
handler_delete.py::contract_delete_delete FAILED                                                                                                         [ 53%]
handler_delete.py::contract_delete_create SKIPPED                                                                                                        [ 61%]
handler_misc.py::contract_check_asserts_work PASSED                                                                                                      [ 69%]
handler_read.py::contract_read_without_create PASSED                                                                                                     [ 76%]
handler_update.py::contract_update_read_success PASSED                                                                                                   [ 84%]
handler_update_invalid.py::contract_update_create_only_property SKIPPED                                                                                  [ 92%]
handler_update_invalid.py::contract_update_non_existent_resource FAILED                                                                                  [100%]
=================================================================== short test summary info ====================================================================
FAILED handler_create.py::contract_invalid_create - AssertionError: status should be FAILED
FAILED handler_delete.py::contract_delete_update - AssertionError: status should be FAILED
FAILED handler_delete.py::contract_delete_delete - AssertionError: status should be FAILED
FAILED handler_update_invalid.py::contract_update_non_existent_resource - AssertionError: status should be FAILED
========================================= 4 failed, 6 passed, 3 skipped, 3 deselected, 9 warnings in 79.60s (0:01:19) ==========================================
```

2020-09-02 15:52 UTC, eduardomourar commented on s3/public-access-block/community-s3-publicaccessblock.json
> +        "list": {
we should remove this if not implemented, that way the contract test will not be run against list operation

2020-09-02 15:52 UTC, eduardomourar commented on s3/public-access-block/src/common.ts
> +    } catch (err) {
this is not necessary because the framework does exactly the same catch you did here: https://github.com/eduardomourar/cloudformation-cli-typescript-plugin/blob/e540a53a8f2a75cd1c51e0e656e2fa68f3d2e4dc/src/resource.ts#L305

2020-09-02 15:52 UTC, eduardomourar commented on s3/public-access-block/src/handlers.ts
> +resource.addHandler(Action.List, WrapHandler(Action.List, 'S3Control', emptyHandler));
this can also be removed

2020-09-02 15:52 UTC, eduardomourar commented on s3/public-access-block/src/common.ts
> +            console.info({ action, message: 'before perform' });
i would suggest the following change to accommodate when the model needs to be modified:
```typescript
console.info({ action, message: 'before perform' });
const modified = await handlerFunc.perform(action, handlerArgs, service);
console.info({ action, message: 'after perform', modified });

progress.status = OperationStatus.Success;
if (modified !== undefined) {
    progress.resourceModel = modified || null;
    progress.resourceModels = null;
}
```

2020-09-02 15:52 UTC, eduardomourar commented on s3/public-access-block/src/handlers.ts
> +    console.info({action, message: 'done'});
for the delete operation a model cannot be passed, so this can be done: `return Promise.resolve(null);`

2020-09-02 15:52 UTC, eduardomourar commented on s3/public-access-block/src/handlers.ts
> +const emptyHandler: ResourceProviderHandler<S3Control> = async (action: Action, args: HandlerArgs, service: S3Control)  => {
we can have a simple read operation like this:
```typescript
const readPublicAccountBlockHandler: ResourceProviderHandler<S3Control> = async (action: Action, args: HandlerArgs, service: S3Control)  => {

    const request: GetPublicAccessBlockRequest = {
        AccountId: args.request.awsAccountId
    };

    console.info({ action, message: 'before invoke getPublicAccessBlock', request });
    try {
        const response = await service.getPublicAccessBlock(request).promise();
        console.info({ action, message: 'after invoke getPublicAccessBlock', response });
    } catch (err) {
        if (err && err.code === 'NoSuchPublicAccessBlockConfiguration') {
            throw new exceptions.NotFound(
                ResourceModel.TYPE_NAME,
                request.AccountId
            );
        } else { // Raise the original exception
            throw err;
        }
    }

    console.info({action, message: 'done'});
    return Promise.resolve(args.request.desiredResourceState);
}
```

2020-09-02 20:13 UTC, OlafConijn commented on s3/public-access-block/src/handlers.ts
> +    putAccountPublicAccessBlock(action, args, {
as discussed:
- We will not adhere to all cfn contract tests. in practice this means you can create an `S3AccountPublicAccessBlock` even if you have already configured something in the account. This also means you can use resources in different regions to modify the same resource.
- We will, later, implement something like a `CfnStrictMode` attribute that, when set to true, will prevent the behavior above. The default however will be false.

2020-09-02 21:27 UTC, OlafConijn commented on s3/public-access-block/src/handlers.ts
> +const emptyHandler: ResourceProviderHandler<S3Control> = async (action: Action, args: HandlerArgs, service: S3Control)  => {
used most of this. did choose to return a ResourceModel based on the response read from AWS.

2020-09-02 21:27 UTC, OlafConijn commented on s3/public-access-block/community-s3-publicaccessblock.json
> +        "list": {
done

2020-09-02 21:28 UTC, OlafConijn commented on s3/public-access-block/src/common.ts
> +    } catch (err) {
done

2020-09-02 21:28 UTC, OlafConijn commented on s3/public-access-block/src/handlers.ts
> +resource.addHandler(Action.List, WrapHandler(Action.List, 'S3Control', emptyHandler));
done

2020-09-02 21:29 UTC, OlafConijn commented on s3/public-access-block/src/common.ts
> +            console.info({ action, message: 'before perform' });
done, || null seems superfluous?

2020-09-03 05:25 UTC, eduardomourar approved these changes

2020-09-03 15:51 UTC, eduardomourar commented
i have tested multiple scenarios (with and without pre-existing resource) using the resource itself based on the example and everything is working as expected:
1. create
2. update (single or multiple properties)
3. delete

we are able to start managing the resource even if they are already there (just like we discussed)

2020-09-03 18:29 UTC, merged