retry create and update upon A conflicting modification in place
org-formation/aws-resource-providers pull request #124
Opened 2023-02-14 20:28 UTC by rene84

The resource Community::Route53::VPCAssociationAuthorization uses the underlying API createVPCAssociationAuthorization. This API will throw an InternalFailure error when there is already another authorization being made.

We encountered this when we wanted to authorize multiple VPCs at once for the same hosted zone. This is actually a retryable error with the message:

`failed because Resource handler returned message: "A conflicting modification to the authorizations in place for xxxxx occurred. Please retry." (RequestToken: xxxxxxx-f3d1-7270-0695-xxxxxx, HandlerErrorCode: InternalFailure).`

This change will make the create and update handler return a ProgressEvent status InProgress so CloudFormation will simply call again later to retry.

2023-02-14 20:45 UTC, eduardomourar requested changes

2023-02-14 20:45 UTC, eduardomourar commented on route53/vpc-association-authorization/src/handlers.ts
> +            if (String(err.message).startsWith('A conflicting modification to the authorizations in place')) {
The message is not guaranteed to be exactly the same, so we actually need to check here for the error name/code like this: https://github.com/aws-cloudformation/cloudformation-cli-typescript-plugin/blob/3b4425127a62d02c6674141e99be2dac4f60e6d6/src/log-delivery.ts#L139

2023-02-14 20:45 UTC, eduardomourar commented on route53/vpc-association-authorization/tsconfig.json
>      "compilerOptions": {
I believe this should be kept and extending the root config. Only leave it whatever needs to be overridden.

2023-02-15 08:54 UTC, rene84 commented on route53/vpc-association-authorization/src/handlers.ts
> +            if (String(err.message).startsWith('A conflicting modification to the authorizations in place')) {
updated to check on code || name. Thanks

2023-02-16 09:45 UTC, merged