Added organizations policy resource
org-formation/aws-resource-providers pull request #28
Opened 2020-10-08 01:49 UTC by thomascollett

Adds a "Community::Organizations::Policy" resource provider which allows for the creation of 4 policy types attached to the root or the OU of AWS Organizations:
* AISERVICES_OPT_OUT_POLICY
* BACKUP_POLICY
* SERVICE_CONTROL_POLICY
* TAG_POLICY

Example CloudFormation template is included as `example.yml`.

Create, update and delete are all supported. Attaching a policy to a different OU currently requires deletion and re-creation of the policy, but the the "update" lifecycle event can be extended to detach and reattach the policy if the target changes. It could also be possible to support a list of target OUs rather than just allowing a single one.

Note: This can only be run in us-east-1 as this is the region within which AWS Organizations allows API calls.

2020-10-08 07:12 UTC, eduardomourar requested changes

2020-10-08 07:12 UTC, eduardomourar commented on organizations/policy/src/handlers.ts
> +    }
the read handler is requirement, so we need to add it here

2020-10-08 07:12 UTC, eduardomourar commented on organizations/policy/src/handlers.ts
> +        console.info({ action, message: 'policy deleted', policyId: policyId });
i am working on [this PR](https://github.com/eduardomourar/cloudformation-cli-typescript-plugin/pull/26) that will change the behavior of how message are logged

2020-10-08 13:22 UTC, OlafConijn commented on organizations/policy/community-organizations-policy.json
> +                "organizations:ListPoliciesForTarget",
do you really need all these permissions?
i only see createPolicy/attachPolicy/updatePolicy/deletePolicy and detachPolicy

2020-10-08 13:26 UTC, OlafConijn commented on organizations/policy/src/handlers.ts
> +    public async create(action: Action, args: HandlerArgs<ResourceModel>, service: Organizations): Promise<ResourceModel> {
would it make sense to enable call EnablePolicyType if not yet enabled? or would that be a different type 🤔

2020-10-08 13:27 UTC, OlafConijn commented on organizations/policy/community-organizations-policy.json
> +        "TargetId": {
should indeed be a list

2020-10-08 14:55 UTC, thomascollett commented on organizations/policy/community-organizations-policy.json
> +                "organizations:ListPoliciesForTarget",
https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_backup_prereqs.html these are the minimum permissions the documentation claims are required for managing backup policies, but I can test it with fewer to see if it still works

2020-10-08 14:58 UTC, thomascollett commented on organizations/policy/src/handlers.ts
> +    public async create(action: Action, args: HandlerArgs<ResourceModel>, service: Organizations): Promise<ResourceModel> {
I agree, let's enable it if not already enabled. I don't see any downside to doing this as the intent of running this by a user is to have a working policy.

2020-10-08 17:58 UTC, thomascollett commented on organizations/policy/src/handlers.ts
> +    public async create(action: Action, args: HandlerArgs<ResourceModel>, service: Organizations): Promise<ResourceModel> {
I found the downside:
`This is an asynchronous request that AWS performs in the background. AWS recommends that you first use ListRoots to see the status of policy types for a specified root, and then use this operation.`
https://docs.aws.amazon.com/cli/latest/reference/organizations/enable-policy-type.html

To do this reliably, we'd need to poll `ListRoots` until it shows as enabled.

2020-10-08 18:53 UTC, thomascollett commented on organizations/policy/src/handlers.ts
> +        console.info({ action, message: 'policy deleted', policyId: policyId });
Looks good, we should move to your logger once that PR is merged.

2020-10-08 19:21 UTC, OlafConijn commented on organizations/policy/src/handlers.ts
> +    public async create(action: Action, args: HandlerArgs<ResourceModel>, service: Organizations): Promise<ResourceModel> {
meh, maybe leave it out for now and add it as an improvement later

2020-10-08 19:21 UTC, OlafConijn approved these changes

2020-10-09 17:53 UTC, eduardomourar commented on organizations/policy/src/handlers.ts
> +    public async create(action: Action, args: HandlerArgs<ResourceModel>, service: Organizations): Promise<ResourceModel> {
Long processes are not that hard and you can check the delay resource to guide you. Agreed that it can be done later.

2020-10-12 19:44 UTC, eduardomourar commented
another general request is to have some basic unit testing in place, otherwise maintaining a monorepo will become an impossible task.

2020-10-22 23:46 UTC, eduardomourar commented on organizations/policy/package.json
> +        "aws-resource-providers-common": "https://github.com/org-formation/aws-resource-providers/releases/download/common-0.2.0/aws-resource-providers-common-0.2.0.tgz",
after rebasing from master, you should update to these dependencies:
```
        "aws-resource-providers-common": "^0.2.0",
        "cfn-rpdk": "npm:@org-formation/cfn-rpdk@^0.4.0",
```

2020-10-22 23:48 UTC, eduardomourar commented
@thomascollett let me know if you need help on rebasing this branch and adding unit testing

2020-10-23 00:01 UTC, thomascollett commented
> @thomascollett let me know if you need help on rebasing this branch and adding unit testing

Thanks - feel free to make changes. It's full-throttle at work right now. I'll have chance to look at this again in the next 1-2 weeks hopefully and implement your recommendations.

2020-10-23 10:39 UTC, eduardomourar commented on organizations/policy/community-organizations-policy.json
> +                "organizations:DescribePolicy"
i believe this was supposed to be `organizations:ListTargetsForPolicy`

2020-10-24 15:56 UTC, eduardomourar commented on organizations/policy/community-organizations-policy.json
> +        "/properties/ResourceId",
resource identifier cannot be a create only property because user will never pass that at all

2020-10-24 16:26 UTC, eduardomourar commented on organizations/policy/src/handlers.ts
> +        } while (response.NextToken);
forget about this suggestion, because applies only to the list handler

2020-10-24 16:27 UTC, eduardomourar commented on organizations/policy/src/handlers.ts
> +    public async listPolicyTargets(service: Organizations, policyId: string): Promise<Organizations.PolicyTargetSummary[]> {
i thought this was the list handler, but it is not, so forget what i said

2020-10-24 16:28 UTC, eduardomourar commented
@thomascollett I have created [this PR](https://github.com/thomascollett/aws-resource-providers/pull/1) targeting your fork with most of my suggested changes.

2020-10-24 19:32 UTC, eduardomourar commented
we need to add a new line for the policy resource in the [main readme](https://github.com/org-formation/aws-resource-providers/blob/master/readme.md) table

2020-10-24 20:07 UTC, eduardomourar commented on organizations/policy/community-organizations-policy.json
> +        "ResourceId": {
after giving some thought, i believe you should use the actual policy ARN. if we also need the id, we rename this to `PolicyId`

2020-10-24 20:27 UTC, eduardomourar commented on organizations/policy/src/handlers.ts
> +        return Promise.resolve(model);
trying to update targetIds property fails with the following message:
> Error: Resource of type 'Community::Organizations::Policy' with identifier 'test-policy' already exists.
because the default behavior in cloudformation is to create a new resource then delete the old one. so we should remove the targetIds from the create only section in the schema. then we can make the update handler, detach everything from previous state then attach the desired state targets.

2020-10-24 20:38 UTC, eduardomourar commented on organizations/policy/community-organizations-policy.json
> +    "createOnlyProperties": [
the `PolicyType` property cannot be updated, so it need to be added to the create only section

2020-11-29 20:43 UTC, merged