chore(iam-saml-provider): use commonAws in saml idp
org-formation/aws-resource-providers pull request #60
Opened 2021-01-13 09:02 UTC by OlafConijn

chore: use commonAws in saml idp
fix: mark arn as 'createOnly' not 'readOnly'

2021-01-13 10:36 UTC, eduardomourar commented
It should not be create only because those properties are expected to be filled that by the customer.

2021-01-13 14:10 UTC, OlafConijn commented
> It should not be create only because those properties are expected to be filled that by the customer.

@eduardomourar ....then what should it be? this a bug in the rpdk?

2021-01-13 19:07 UTC, eduardomourar commented
Not a bug. It just that we need to instantiate a new ResourceModel because the desired state is immutable

2021-01-13 19:25 UTC, OlafConijn commented
right.... so that started when a dependency got updated where the desiredModel became immutable? 
maybe makes sense to update the errorMessage. i think this is the second time we got bit by it

2021-01-13 21:27 UTC, eduardomourar commented
Yes, I believe that started on v0.3.0+. I will create a issue for it. FYI, I have made that clear in new the aws blog post.

2021-01-14 20:36 UTC, eduardomourar requested changes

2021-01-14 20:36 UTC, eduardomourar commented on iam/oidc-providers/package.json
>          "aws-resource-providers-common": "^0.2.0",
this should be update to 0.3.0 and the lock file should be recreated as well

2021-01-14 20:43 UTC, eduardomourar commented on iam/saml-provider/package.json
> +        "aws-resource-providers-common": "^0.2.0",
this should be 0.3.0 and lock file update

2021-01-14 20:46 UTC, eduardomourar commented
the schema should also contain `replacementStrategy: delete_then_create` because that will be needed for most global resources

2021-01-17 21:07 UTC, eduardomourar commented on iam/oidc-providers/package.json
>          "class-transformer": "^0.3.1"
i found an issue with the library `class-transformer` that you are probably facing. they introduced a breaking change. so we need to force the version we used:
```
"class-transformer": "0.3.1"
```

2021-01-17 21:07 UTC, eduardomourar commented on iam/saml-provider/package.json
>          "class-transformer": "^0.3.1"
same here:
```
"class-transformer": "0.3.1"
```

2021-01-17 23:27 UTC, OlafConijn commented
> the schema should also contain `replacementStrategy: delete_then_create` because that will be needed for most global resources

not sure whether i follow. i assume with global you mean not-regional resources. what would the benefit be of delete_then_create? In my understanding delete_then_create makes it possible to rename the logical-id and global resources (1 per account) with a good default (no outage) would benefit from that, but i dont see that benefit here

2021-01-18 00:30 UTC, eduardomourar commented
> > the schema should also contain `replacementStrategy: delete_then_create` because that will be needed for most global resources
> 
> not sure whether i follow. i assume with global you mean not-regional resources. what would the benefit be of delete_then_create? In my understanding delete_then_create makes it possible to rename the logical-id and global resources (1 per account) with a good default (no outage) would benefit from that, but i dont see that benefit here

yes, you are right. it makes sense to have that in the password policy. forget i said anything

2021-01-18 00:53 UTC, eduardomourar approved these changes
LGTM

2021-01-18 07:51 UTC, merged