Feat/service quotas dynamodb
org-formation/aws-resource-providers pull request #63
Opened 2021-01-18 00:29 UTC by OlafConijn

*Issue #, if available:*

*Description of changes:*

2021-02-15 22:58 UTC, eduardomourar requested changes

2021-02-15 22:58 UTC, eduardomourar commented on iam/saml-provider/community-iam-samlprovider.json
> +    "createOnlyProperties": [
i think this change to the iam saml provider was not supposed to be here. because readonly is the right approach

2021-02-15 23:00 UTC, OlafConijn commented on iam/saml-provider/community-iam-samlprovider.json
> +    "createOnlyProperties": [
right, thanks for spotting that!

2021-02-15 23:02 UTC, OlafConijn commented on iam/saml-provider/community-iam-samlprovider.json
> +    "createOnlyProperties": [
you clearly have an eye for this... maybe you should make it your profession ;) <3

2021-02-15 23:08 UTC, eduardomourar commented
we need to change line 32 in the cicd.yml file to: `pip install --upgrade pip aws-sam-cli git+https://github.com/eduardomourar/cloudformation-cli-nodejs-plugin.git` otherwise the pipeline just hangs forever

2021-02-15 23:42 UTC, eduardomourar approved these changes

2021-02-15 23:43 UTC, OlafConijn commented
> we need to change line 32 in the cicd.yml file to: `pip install --upgrade pip aws-sam-cli git+https://github.com/eduardomourar/cloudformation-cli-nodejs-plugin.git` otherwise the pipeline just hangs forever

i think its still hanging? fix later?

2021-02-16 00:18 UTC, eduardomourar commented
Yes, because I need to dig deeper into the problem

2022-01-22 09:55 UTC, merged